### ISSUE TITLE
请问你有51822开发板的资料吗

### ISSUE THREAD

**Issue by benzhiqiang** [weimingtom/wmt_nrf_study#1]

**Comment by weimingtom** [comment]
没有，我只在csdn上找到一些关于nrf51822手环代码之类，或者在一些代码下载站可以找到，例如源码中国ymcn之类

**Comment by weimingtom** [comment]
我想起来了，还有这个，微雪的资料wiki：

- https://www.waveshare.net/wiki/Core51822
- https://www.waveshare.net/wiki/BLE400

微雪的教程还是很详细的，虽然很多时候我都是自己想，懒得看它怎么用

**Comment by weimingtom** [comment]
当然怎么都不如去看nordic的官网讲得详细
